#!/bin/bash

if [ -n "$1" ]; then
  QSTAT=`qstat -f $1  -Fdsv`
  arrQSTAT=(${QSTAT//|/ })
  EXECHOSTFULL=${arrQSTAT[21]}
  arrEXECHOSTFULL=(${EXECHOSTFULL//=/ })
  EXECHOST=`sed "s/\/0\*16//g" <<<"${arrEXECHOSTFULL[1]}"`
  HOSTS=(${EXECHOST//+/ })

  for i in "${HOSTS[@]}"
  do
    echo $i
    ssh $i "cat /proc/cpuinfo|grep MHz|uniq"
  done
else
  echo "$0 JOBID"
fi
